database_host: 'localhost'
database_name: 'simple_transaction'
database_port: '3306'
database_user: 'root'
database_password: 'root'
user_login: 'mike123'
user_password: '123456'
user_name: 'Mike'
user_amount: 120.00